name: Trace pods

on:
    push:
      branches:
        - k8s
    schedule:
      - cron: '5 * * * *'

jobs:
    production:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@master
            
            - name: setup ssh
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
                echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/config
                # ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
              shell: bash

            - name: setup configs k*s
              run: |
                mkdir -p ~/.kube
                echo "${{ secrets.CONFIG_K8S }}" > ~/.kube/config-k8s
                echo "${{ secrets.CONFIG_K3S }}" > ~/.kube/config-k3s
                export KUBECONFIG=$HOME/.kube/onfig-k8s
                export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-k3s

            - name: kubectl get pods --context=k8s
              uses: actions-hub/kubectl@master
              with:
                args: get pods -A --context=k8s

            - name: kubectl get pods --context=k3s
              uses: actions-hub/kubectl@master
              with:
                args: get pods -A --context=k3s
