name: Trace pods

on:
    push:
      branches:
        - k8s
    schedule:
      - cron: '5 * * * *'

jobs:
    k8s:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@master
            
            # - name: setup ssh
            #   run: |
            #     mkdir -p ~/.ssh
            #     chmod 700 ~/.ssh
            #     touch ~/.ssh/id_rsa
            #     echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
            #     chmod 600 ~/.ssh/id_rsa
            #     touch ~/.ssh/id_rsa.pub
            #     echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
            #     chmod 600 ~/.ssh/id_rsa.pub
            #     touch ~/.ssh/config
            #     echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
            #     chmod 644 ~/.ssh/config
            #     touch ~/.ssh/known_hosts
            #     echo "${{ secrets.SSH_KNOW_HOST }}" > ~/.ssh/known_hosts
            #     chmod 644 ~/.ssh/known_hosts
            #     ssh -i ~/.ssh/id_rsa -L 6443:127.0.0.1:6443 root@192.168.208.5 -f -N
            #     sudo lsof -i -n -P | grep -E '^sshd\>'
            #     sudo lsof -i -n -P | grep -E '^ssh\>'
            #   shell: bash

            - name: setup ssh
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}

            # - name: Create SSH tunnel
            #   run:
            #     ssh -i  -L 6443:127.0.0.1:6443 root@192.168.208.5 -f -N

            # - name: Install kubectl
            #   run: |
            #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            #     chmod +x kubectl
            #     sudo mv kubectl /usr/local/bin/
            #     kubectl version
    
            # - name: Check Kubernetes Nodes
            #   run: |
            #     echo "${{ secrets.CONFIG_K8S }}" > $HOME/.kube/config
            #     export KUBECONFIG=$HOME/.kube/config
            #     kubectl get nodes

            - name: kubectl get pods
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.CONFIG_K8S }}
              with:
                args: get pods

    # k3s:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: checkout repository
    #           uses: actions/checkout@master
            
    #         - name: setup ssh
    #           run: |
    #             mkdir -p ~/.ssh
    #             chmod 700 ~/.ssh
    #             touch ~/.ssh/id_rsa
    #             echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
    #             chmod 600 ~/.ssh/id_rsa
    #             touch ~/.ssh/id_rsa.pub
    #             echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
    #             chmod 600 ~/.ssh/id_rsa.pub
    #             touch ~/.ssh/config
    #             echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
    #             chmod 644 ~/.ssh/config
    #             touch ~/.ssh/known_hosts
    #             echo "${{ secrets.SSH_KNOW_HOST }}" > ~/.ssh/known_hosts
    #             chmod 644 ~/.ssh/known_hosts
    #             ssh -L 6444:127.0.0.1:6443 root@192.168.203.3 -f -N
    #             sudo lsof -i -n -P | grep -E '^sshd\>'
    #             sudo lsof -i -n -P | grep -E '^ssh\>'
    #           shell: bash

    #         - name: kubectl get pods
    #           uses: actions-hub/kubectl@master
    #           env:
    #             KUBE_CONFIG: ${{ secrets.CONFIG_K3S }}
    #           with:
    #             args: get pods
