name: Trace pods

on:
    push:
      branches:
        - k8s
    schedule:
      - cron: '5 * * * *'

jobs:
    production:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@master

            # - name: setup kubectl
            #   run: |
            #     sudo apt-get update
            #     sudo apt-get install -y apt-transport-https ca-certificates curl
            #     curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
            #     echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
            #     sudo apt-get update
            #     sudo apt-get install -y kubectl
            
            - name: setup ssh
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
                echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/config
                # ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
              shell: bash

            - name: setup configs k*s
              run: |
                mkdir -p ~/.kube
                echo "${{ secrets.CONFIG_K8S }}" > ~/.kube/config-k8s
                echo "${{ secrets.CONFIG_K3S }}" > ~/.kube/config-k3s
                export KUBECONFIG=$HOME/.kube/onfig-k8s
                export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-k3s

            - name: kubectl get pods --context=k8s
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.CONFIG_K8S }}
              with:
                args: get pods -A --context=k8s

            - name: kubectl get pods --context=k3s
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.CONFIG_K3S }}
              with:
                args: get pods -A --context=k3s
                
            # - name: check k8s
            #   run: |
            #     kubectl get pods -A --context=k8s

            # - name: check k3s
            #   run: |
            #     kubectl get pods -A --context=k3s
