name: Trace pods

on:
    push:
      branches:
        - k8s
    schedule:
      - cron: '5 * * * *'

jobs:
    k8s:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@master
            
            - name: setup ssh
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
                echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/config
                echo "${{ secrets.SSH_KNOW_HOST }}" > ~/.ssh/known_hosts
                ssh -L 6443:127.0.0.1:6443 root@192.168.208.5 -f -N
              shell: bash

            - name: setup configs k8s
              run: |
                mkdir -p ~/.kube
                echo "${{ secrets.CONFIG_K8S }}" > ~/.kube/config-k8s
                # export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-k8s

            - name: kubectl get pods
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.CONFIG_K8S }}
              with:
                args: get pods

    k3s:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@master
            
            - name: setup ssh
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
                echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
                echo "${{ secrets.CONFIG_SSH }}" > ~/.ssh/config
                chmod 600 ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa.pub
                chmod 600 ~/.ssh/config
                echo "${{ secrets.SSH_KNOW_HOST }}" > ~/.ssh/known_hosts
                ssh -L 6443:127.0.0.1:6443 root@192.168.203.3 -f -N
              shell: bash

            - name: setup configs k3s
              run: |
                mkdir -p ~/.kube
                echo "${{ secrets.CONFIG_K3S }}" > ~/.kube/config-k3s
                # export KUBECONFIG=$KUBECONFIG:$HOME/.kube/config-k3s

            - name: kubectl get pods
              uses: actions-hub/kubectl@master
              env:
                KUBE_CONFIG: ${{ secrets.CONFIG_K3S }}
              with:
                args: get pods
