# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - main

jobs:

  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]


    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    # You can printing the current Go version
    - name: Display Go version
      run: go version

    # - name: Build
    #   run: go build -v ./cmd/...

    - name: Test
      run: go test -v ./cmd...

    - name: Test with Go
      run: go test -json ./cmd... > TestResults-${{ matrix.go-version }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
